//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:v2.0.50727
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

/*
This code was automatically generated at 02/18/2012 18:38:25 by 
        Jedzia's ViewModel generator.
Changes to this file may be lost if regeneration occurs.
http://xxx.com
*/
// Config = Debug DefaultNamespace = Jedzia.BackBock.ViewModel

using System.Collections.Generic;
using Jedzia.BackBock.SharedTypes;
using Jedzia.BackBock.Model.Data;
using Jedzia.BackBock.ViewModel.MainWindow;


namespace Jedzia.BackBock.ViewModel.Data.Hierarchical
{

    /// <summary>
    /// The summary of MethodsViewModel. BaseType: ClassMember
    /// </summary>
    public partial class MethodsViewModel : ClassMemberViewModel
    {
        internal Method methods;

        public MethodsViewModel(Method methods)
            : base(methods)
        {
            this.methods = methods;
        }

        // Signature. HasFacets: False AttrQName: 
        //                   propertyType: System.String, IsChoiceRoot: False, BaseType: 
        //                   ListType: None, HasCommonBaseType: False, xxxx: 
        /// <summary>
        /// Gets or sets the Signature. HasFacets: False AttrQName: 
        /// </summary> // Attribute
        /// <value>The Signature.</value>
        public System.String Signature
        {
            get
            {
                return this.methods.Signature;
            }

            set
            {
                if (this.methods.Signature == value)
                {
                    return;
                }
                this.methods.Signature = value;
                RaisePropertyChanged("Signature");
            }
        }

        // Scope. HasFacets: True AttrQName: ScopeType
        //                   propertyType: System.String, IsChoiceRoot: False, BaseType: 
        //                   ListType: None, HasCommonBaseType: False, xxxx: 
        /// <summary>
        /// Gets or sets the Scope. HasFacets: True AttrQName: ScopeType
        /// </summary> // Attribute
        /// <value>The Scope.</value>
        public ScopeType Scope
        {
            get
            {
                return this.methods.Scope;
            }

            set
            {
                if (this.methods.Scope == value)
                {
                    return;
                }
                this.methods.Scope = value;
                RaisePropertyChanged("Scope");
            }
        }

        // ReturnType. HasFacets: True AttrQName: MethodReturnType
        //                   propertyType: System.String, IsChoiceRoot: False, BaseType: 
        //                   ListType: None, HasCommonBaseType: False, xxxx: 
        /// <summary>
        /// Gets or sets the ReturnType. HasFacets: True AttrQName: MethodReturnType
        /// </summary> // Attribute
        /// <value>The ReturnType.</value>
        public MethodReturnType ReturnType
        {
            get
            {
                return this.methods.ReturnType;
            }

            set
            {
                if (this.methods.ReturnType == value)
                {
                    return;
                }
                this.methods.ReturnType = value;
                RaisePropertyChanged("ReturnType");
            }
        }

        // Parameternames. HasFacets: False AttrQName: 
        //                   propertyType: System.String, IsChoiceRoot: False, BaseType: 
        //                   ListType: None, HasCommonBaseType: False, xxxx: 
        /// <summary>
        /// Gets or sets the Parameternames. HasFacets: False AttrQName: 
        /// </summary> // Attribute
        /// <value>The Parameternames.</value>
        public System.String Parameternames
        {
            get
            {
                return this.methods.Parameternames;
            }

            set
            {
                if (this.methods.Parameternames == value)
                {
                    return;
                }
                this.methods.Parameternames = value;
                RaisePropertyChanged("Parameternames");
            }
        }

        // IsConstructor. HasFacets: False AttrQName: 
        //                   propertyType: System.Boolean, IsChoiceRoot: False, BaseType: 
        //                   ListType: None, HasCommonBaseType: False, xxxx: 
        /// <summary>
        /// Gets or sets the IsConstructor. HasFacets: False AttrQName: 
        /// </summary> // Attribute
        /// <value>The IsConstructor.</value>
        public System.Boolean IsConstructor
        {
            get
            {
                return this.methods.IsConstructor;
            }

            set
            {
                if (this.methods.IsConstructor == value)
                {
                    return;
                }
                this.methods.IsConstructor = value;
                RaisePropertyChanged("IsConstructor");
            }
        }

        protected virtual void OnDataPropertyChanged(object sender, System.ComponentModel.PropertyChangedEventArgs e)
        {
            DataPropertyChanged(sender, e);
        }

        partial void DataPropertyChanged(object sender, System.ComponentModel.PropertyChangedEventArgs e);

        public MethodsViewModel Clone()
        {
            return (MethodsViewModel)this.MemberwiseClone();
        }
    } 
}
