//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:v2.0.50727
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

/*
This code was automatically generated at 02/18/2012 18:38:25 by 
        Jedzia's ViewModel generator.
Changes to this file may be lost if regeneration occurs.
http://xxx.com
*/
// Config = Debug DefaultNamespace = Jedzia.BackBock.ViewModel

using System.Collections.Generic;
using Jedzia.BackBock.SharedTypes;
using Jedzia.BackBock.Model.Data;
using Jedzia.BackBock.ViewModel.MainWindow;


namespace Jedzia.BackBock.ViewModel.Data.Hierarchical
{

    /// <summary>
    /// The summary of SpecificationViewModel. BaseType: ClassMember
    /// </summary>
    public partial class SpecificationViewModel : ClassMemberViewModel
    {
        internal SpecificationType specification;

        public SpecificationViewModel(SpecificationType specification)
            : base(specification)
        {
            this.specification = specification;
        }

        // Specs. HasFacets: False AttrQName: 
        //                   propertyType: System.Double, IsChoiceRoot: False, BaseType: 
        //                   ListType: None, HasCommonBaseType: False, xxxx: 
        /// <summary>
        /// Gets or sets the Specs. HasFacets: False AttrQName: 
        /// </summary> // Attribute
        /// <value>The Specs.</value>
        public System.Double Specs
        {
            get
            {
                return this.specification.Specs;
            }

            set
            {
                if (this.specification.Specs == value)
                {
                    return;
                }
                this.specification.Specs = value;
                RaisePropertyChanged("Specs");
            }
        }

        protected virtual void OnDataPropertyChanged(object sender, System.ComponentModel.PropertyChangedEventArgs e)
        {
            DataPropertyChanged(sender, e);
        }

        partial void DataPropertyChanged(object sender, System.ComponentModel.PropertyChangedEventArgs e);

        public SpecificationViewModel Clone()
        {
            return (SpecificationViewModel)this.MemberwiseClone();
        }
    } 
}
