
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:v2.0.50727
//     ViewModelGenerator:v1.0
//
//     Changes to this and other generated files may cause incorrect behavior 
//     and will be lost if the code is regenerated.
// </auto-generated>
//
// Important: 
// This code generator needs a registry key set to run. Make sure
// HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\VisualStudio\9.0\TextTemplating\IncludeFolders\.tt\IncludeJedziaT4Tools
// points to the location of the T4 Directory, e.g. "D:\JedziaT4Tools\T4" (without the quotes). 
// Then create a system environment variable with the name "JEDZIAT4TOOLS" and point it to the same
// location as the T4-Include registry key.
//------------------------------------------------------------------------------



   // ==========================================================================
   // vmodel.Name : ClassData | vmodel.Type : ClassData | 

        //  item.Name : Items | item.Type : System.Object | propertyType : ClassDataItems  
        //  item.Name : Name | item.Type : System.String | propertyType : ClassDataName  
   // ==========================================================================


   // ==========================================================================
   // vmodel.Name : DerivedFrom | vmodel.Type : Derive | 

        //  item.Name : Test | item.Type : System.String | propertyType : DeriveTest  
        //  item.Name : Nix | item.Type : System.Boolean | propertyType : DeriveNix  
        //  item.Name : Rotz | item.Type : System.Boolean | propertyType : DeriveRotz  
        //  item.Name : Blafasel | item.Type : System.DateTime | propertyType : DeriveBlafasel  
        //  item.Name : IsInterface | item.Type : System.Boolean | propertyType : DeriveIsInterface  
   // ==========================================================================


   // ==========================================================================
   // vmodel.Name : ClassMember | vmodel.Type : ClassMember | 

        //  item.Name : Name | item.Type : System.String | propertyType : ClassMemberName  
   // ==========================================================================


   // ==========================================================================
   // vmodel.Name : Fields | vmodel.Type : Field | 

        // ***WithFacets*** item.Name : ValueType | item.Type : System.String | propertyType : FieldValueType ***WithFacets*** 
        //  item.Name : IsStatic | item.Type : System.Boolean | propertyType : FieldIsStatic  
        // ***WithFacets*** item.Name : Scope | item.Type : System.String | propertyType : ScopeType ***WithFacets*** 
   // ==========================================================================


   // ==========================================================================
   // vmodel.Name : Properties | vmodel.Type : Property | 

        // ***WithFacets*** item.Name : ValueType | item.Type : System.String | propertyType : FieldValueType ***WithFacets*** 
        // ***WithFacets*** item.Name : Scope | item.Type : System.String | propertyType : ScopeType ***WithFacets*** 
   // ==========================================================================


   // ==========================================================================
   // vmodel.Name : Methods | vmodel.Type : Method | 

        //  item.Name : Signature | item.Type : System.String | propertyType : MethodSignature  
        // ***WithFacets*** item.Name : Scope | item.Type : System.String | propertyType : ScopeType ***WithFacets*** 
        // ***WithFacets*** item.Name : ReturnType | item.Type : System.String | propertyType : MethodReturnType ***WithFacets*** 
        //  item.Name : Parameternames | item.Type : System.String | propertyType : MethodParameternames  
        //  item.Name : IsConstructor | item.Type : System.Boolean | propertyType : MethodIsConstructor  
   // ==========================================================================


   // ==========================================================================
   // vmodel.Name : Specification | vmodel.Type : SpecificationType | 

        //  item.Name : Specs | item.Type : System.Double | propertyType : SpecificationTypeSpecs  
   // ==========================================================================


   // ==========================================================================
   // vmodel.Name : Randale | vmodel.Type : Randale | 

        //  item.Name : Name | item.Type : System.String | propertyType : RandaleName  
   // ==========================================================================


