// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.38967
//    <NameSpace>Jedzia.BackBock.DataAccess.DTO</NameSpace><Collection>Array</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net35</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>False</GenerateXMLAttributes><EnableEncoding>False</EnableEncoding><AutomaticProperties>True</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>None</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>False</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace Jedzia.BackBock.DataAccess.DTO
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;


    public partial class BackupData
    {

        private BackupItemType[] backupItemField;


        public string DatasetName { get; set; }

        public string DatasetGroup { get; set; }


        public BackupItemType[] BackupItem
        {
            get
            {
                return this.backupItemField;
            }
            set
            {
                this.backupItemField = value;
            }
        }
    }

    public partial class BackupItemType
    {

        private PathDataType[] pathField;

        private TaskType taskField;

        private bool isEnabledField;

        public string ItemName { get; set; }

        public string ItemGroup { get; set; }


        public BackupItemType()
        {
            this.isEnabledField = false;
        }

        public PathDataType[] Path
        {
            get
            {
                return this.pathField;
            }
            set
            {
                this.pathField = value;
            }
        }

        public TaskType Task
        {
            get
            {
                return this.taskField;
            }
            set
            {
                this.taskField = value;
            }
        }

        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool IsEnabled
        {
            get
            {
                return this.isEnabledField;
            }
            set
            {
                this.isEnabledField = value;
            }
        }
    }

    public partial class PathDataType
    {

        private Wildcard[] exclusionField;

        private Wildcard[] inclusionField;

        public string Path { get; set; }

        public string UserData { get; set; }


        public Wildcard[] Exclusion
        {
            get
            {
                return this.exclusionField;
            }
            set
            {
                this.exclusionField = value;
            }
        }

        public Wildcard[] Inclusion
        {
            get
            {
                return this.inclusionField;
            }
            set
            {
                this.inclusionField = value;
            }
        }
    }

    public partial class Wildcard
    {

        private bool enabledField;

        public string Pattern { get; set; }


        public Wildcard()
        {
            this.enabledField = false;
        }

        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool Enabled
        {
            get
            {
                return this.enabledField;
            }
            set
            {
                this.enabledField = value;
            }
        }
    }

    public partial class TaskType
    {

        private System.Xml.XmlAttribute[] anyAttrField;

        public string TypeName { get; set; }


        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr
        {
            get
            {
                return this.anyAttrField;
            }
            set
            {
                this.anyAttrField = value;
            }
        }
    }
}
