
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:v2.0.50727
//     DTOGenerator:v1.0
//
//     Changes to this and other generated files may cause incorrect behavior 
//     and will be lost if the code is regenerated.
// </auto-generated>
//
// Important: 
// This code generator needs a registry key set to run. Make sure
// HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\VisualStudio\9.0\TextTemplating\IncludeFolders\.tt\IncludeJedziaT4Tools
// points to the location of the T4 Directory, e.g. "D:\JedziaT4Tools\T4" (without the quotes). 
// Then create a system environment variable with the name "JEDZIAT4TOOLS" and point it to the same
// location as the T4-Include registry key.
//------------------------------------------------------------------------------



/*
This code was automatically generated at 03/26/2012 08:47:48 by 
        Jedzia's Template generator.
Changes to this file may be lost if regeneration occurs.
http://xxx.com
*/
// Config = Debug DefaultNamespace = Jedzia.BackBock.DataAccess

using System.Collections.Generic;


namespace Jedzia.BackBock.DataAccess.DTO
{

    /// <summary>
    /// The summary of Path. BaseType: 
    /// </summary>
    public partial class PathDataType// : ViewModelBase
    {
        /// <summary>
        /// Gets or sets the Exclusion.
        /// </summary>
        /// <value>The Exclusion.</value>
        public Wildcard[] Exclusion
        {
            get;
            set;
        }

        /// <summary>
        /// Gets or sets the Inclusion.
        /// </summary>
        /// <value>The Inclusion.</value>
        public Wildcard[] Inclusion
        {
            get;
            set;
        }

        /// <summary>
        /// Gets or sets the Path.
        /// </summary>
        /// <value>The Path.</value>
        public System.String Path
        {
            get;
            set;
        }

        /// <summary>
        /// Gets or sets the UserData.
        /// </summary>
        /// <value>The UserData.</value>
        public System.String UserData
        {
            get;
            set;
        }

    }

    /// <summary>
    /// The summary of Exclusion. BaseType: 
    /// </summary>
    public partial class Wildcard// : ViewModelBase
    {
        /// <summary>
        /// Gets or sets the Pattern.
        /// </summary>
        /// <value>The Pattern.</value>
        public System.String Pattern
        {
            get;
            set;
        }

        /// <summary>
        /// Gets or sets the Enabled.
        /// </summary>
        /// <value>The Enabled.</value>
        public System.Boolean Enabled
        {
            get;
            set;
        }

    }

    /// <summary>
    /// The summary of Task. BaseType: 
    /// </summary>
    public partial class TaskType// : ViewModelBase
    {
        /// <summary>
        /// Gets or sets the TypeName.
        /// </summary>
        /// <value>The TypeName.</value>
        public System.String TypeName
        {
            get;
            set;
        }

        public System.Xml.XmlAttribute[] AnyAttr
        {
            get;
            set;
        }
    }

    /// <summary>
    /// The summary of BackupData. BaseType: 
    /// </summary>
    public partial class BackupData// : ViewModelBase
    {
        /// <summary>
        /// Gets or sets the BackupItem.
        /// </summary>
        /// <value>The BackupItem.</value>
        public BackupItemType[] BackupItem
        {
            get;
            set;
        }

        /// <summary>
        /// Gets or sets the DatasetName.
        /// </summary>
        /// <value>The DatasetName.</value>
        public System.String DatasetName
        {
            get;
            set;
        }

        /// <summary>
        /// Gets or sets the DatasetGroup.
        /// </summary>
        /// <value>The DatasetGroup.</value>
        public System.String DatasetGroup
        {
            get;
            set;
        }

    }

    /// <summary>
    /// The summary of BackupItem. BaseType: 
    /// </summary>
    public partial class BackupItemType// : ViewModelBase
    {
        /// <summary>
        /// Gets or sets the Path.
        /// </summary>
        /// <value>The Path.</value>
        public PathDataType[] Path
        {
            get;
            set;
        }

        /// <summary>
        /// Gets or sets the Task.
        /// </summary>
        /// <value>The Task.</value>
        public TaskType Task
        {
            get;
            set;
        }

        /// <summary>
        /// Gets or sets the ItemName.
        /// </summary>
        /// <value>The ItemName.</value>
        public System.String ItemName
        {
            get;
            set;
        }

        /// <summary>
        /// Gets or sets the ItemGroup.
        /// </summary>
        /// <value>The ItemGroup.</value>
        public System.String ItemGroup
        {
            get;
            set;
        }

        /// <summary>
        /// Gets or sets the IsEnabled.
        /// </summary>
        /// <value>The IsEnabled.</value>
        public System.Boolean IsEnabled
        {
            get;
            set;
        }

    }
}
