
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:v2.0.50727
//     ViewModelGenerator:v1.0
//
//     Changes to this and other generated files may cause incorrect behavior 
//     and will be lost if the code is regenerated.
// </auto-generated>
//
// Important: 
// This code generator needs a registry key set to run. Make sure
// HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\VisualStudio\9.0\TextTemplating\IncludeFolders\.tt\IncludeJedziaT4Tools
// points to the location of the T4 Directory, e.g. "D:\JedziaT4Tools\T4" (without the quotes). 
// Then create a system environment variable with the name "JEDZIAT4TOOLS" and point it to the same
// location as the T4-Include registry key.
//------------------------------------------------------------------------------



   // ==========================================================================
   // vmodel.Name : Paths | vmodel.Type : Paths | 

        //  item.Name : Exclusion | item.Type : Wildcard | propertyType : PathsExclusion  
        //  item.Name : Inclusion | item.Type : Wildcard | propertyType : PathsInclusion  
        //  item.Name : Path | item.Type : System.String | propertyType : PathsPath  
        //  item.Name : UserData | item.Type : System.String | propertyType : PathsUserData  
   // ==========================================================================


   // ==========================================================================
   // vmodel.Name : Exclusion | vmodel.Type : Wildcard | 

        //  item.Name : Pattern | item.Type : System.String | propertyType : WildcardPattern  
        //  item.Name : Enabled | item.Type : System.Boolean | propertyType : WildcardEnabled  
   // ==========================================================================


   // ==========================================================================
   // vmodel.Name : Inclusion | vmodel.Type : Wildcard | 

        //  item.Name : Pattern | item.Type : System.String | propertyType : WildcardPattern  
        //  item.Name : Enabled | item.Type : System.Boolean | propertyType : WildcardEnabled  
   // ==========================================================================


   // ==========================================================================
   // vmodel.Name : BackupData | vmodel.Type : BackupData | 

        //  item.Name : BackupItem | item.Type : BackupItem | propertyType : BackupDataBackupItem  
        //  item.Name : Name | item.Type : System.String | propertyType : BackupDataName  
   // ==========================================================================


   // ==========================================================================
   // vmodel.Name : BackupItem | vmodel.Type : BackupItem | 

        //  item.Name : Paths | item.Type : Paths | propertyType : BackupItemPaths  
        //  item.Name : Name | item.Type : System.String | propertyType : BackupItemName  
        //  item.Name : IsEnabled | item.Type : System.Boolean | propertyType : BackupItemIsEnabled  
   // ==========================================================================


