//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:v2.0.50727
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

/*
This code was automatically generated at 02/19/2012 14:24:14 by 
        Jedzia's ViewModel generator.
Changes to this file may be lost if regeneration occurs.
http://xxx.com
*/
// Config = Debug DefaultNamespace = Jedzia.BackBock.ViewModel

using System.Collections.Generic;
using Jedzia.BackBock.SharedTypes;
using Jedzia.BackBock.Model.Data;
using Jedzia.BackBock.ViewModel.MainWindow;


namespace Jedzia.BackBock.ViewModel.Data
{

    /// <summary>
    /// The summary of InclusionViewModel. BaseType: 
    /// </summary>
    public partial class InclusionViewModel : ViewModelBase
    {
        internal Wildcard inclusion;

        public InclusionViewModel(Wildcard inclusion)
        {
            this.inclusion = inclusion;
        }

        // Pattern. HasFacets: False AttrQName: 
        //                   propertyType: System.String, IsChoiceRoot: False, BaseType: 
        //                   ListType: None, HasCommonBaseType: False, xxxx: 
        /// <summary>
        /// Gets or sets the Pattern. HasFacets: False AttrQName: 
        /// </summary> // Attribute
        /// <value>The Pattern.</value>
        public System.String Pattern
        {
            get
            {
                return this.inclusion.Pattern;
            }

            set
            {
                if (this.inclusion.Pattern == value)
                {
                    return;
                }
                this.inclusion.Pattern = value;
                RaisePropertyChanged("Pattern");
            }
        }

        // Enabled. HasFacets: False AttrQName: 
        //                   propertyType: System.Boolean, IsChoiceRoot: False, BaseType: 
        //                   ListType: None, HasCommonBaseType: False, xxxx: 
        /// <summary>
        /// Gets or sets the Enabled. HasFacets: False AttrQName: 
        /// </summary> // Attribute
        /// <value>The Enabled.</value>
        public System.Boolean Enabled
        {
            get
            {
                return this.inclusion.Enabled;
            }

            set
            {
                if (this.inclusion.Enabled == value)
                {
                    return;
                }
                this.inclusion.Enabled = value;
                RaisePropertyChanged("Enabled");
            }
        }

        protected virtual void OnDataPropertyChanged(object sender, System.ComponentModel.PropertyChangedEventArgs e)
        {
            DataPropertyChanged(sender, e);
        }

        partial void DataPropertyChanged(object sender, System.ComponentModel.PropertyChangedEventArgs e);

        public InclusionViewModel Clone()
        {
            return (InclusionViewModel)this.MemberwiseClone();
        }
    } 
}
