
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:v2.0.50727
//     ViewModelGenerator:v1.0
//
//     Changes to this and other generated files may cause incorrect behavior 
//     and will be lost if the code is regenerated.
// </auto-generated>
//
// Important: 
// This code generator needs a registry key set to run. Make sure
// HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\VisualStudio\9.0\TextTemplating\IncludeFolders\.tt\IncludeJedziaT4Tools
// points to the location of the T4 Directory, e.g. "D:\JedziaT4Tools\T4" (without the quotes). 
// Then create a system environment variable with the name "JEDZIAT4TOOLS" and point it to the same
// location as the T4-Include registry key.
//------------------------------------------------------------------------------



   // ==========================================================================
   // vmodel.Name : Path | vmodel.Type : PathDataType | 

        //  item.Name : Exclusion | item.Type : Wildcard | propertyType : PathDataTypeExclusion  
        //  item.Name : Inclusion | item.Type : Wildcard | propertyType : PathDataTypeInclusion  
        //  item.Name : Path | item.Type : System.String | propertyType : PathDataTypePath  
        //  item.Name : UserData | item.Type : System.String | propertyType : PathDataTypeUserData  
   // ==========================================================================


   // ==========================================================================
   // vmodel.Name : Exclusion | vmodel.Type : Wildcard | 

        //  item.Name : Pattern | item.Type : System.String | propertyType : WildcardPattern  
        //  item.Name : Enabled | item.Type : System.Boolean | propertyType : WildcardEnabled  
   // ==========================================================================


   // ==========================================================================
   // vmodel.Name : Inclusion | vmodel.Type : Wildcard | 

        //  item.Name : Pattern | item.Type : System.String | propertyType : WildcardPattern  
        //  item.Name : Enabled | item.Type : System.Boolean | propertyType : WildcardEnabled  
   // ==========================================================================


   // ==========================================================================
   // vmodel.Name : Task | vmodel.Type : TaskType | 

        //  item.Name : TypeName | item.Type : System.String | propertyType : TaskTypeTypeName  
   // ==========================================================================


   // ==========================================================================
   // vmodel.Name : BackupData | vmodel.Type : BackupData | 

        //  item.Name : BackupItem | item.Type : BackupItemType | propertyType : BackupDataBackupItem  
        //  item.Name : DatasetName | item.Type : System.String | propertyType : BackupDataDatasetName  
   // ==========================================================================


   // ==========================================================================
   // vmodel.Name : BackupItem | vmodel.Type : BackupItemType | 

        //  item.Name : Path | item.Type : Path | propertyType : BackupItemTypePath  
        //  item.Name : Task | item.Type : TaskType | propertyType : BackupItemTypeTask  
        //  item.Name : ItemName | item.Type : System.String | propertyType : BackupItemTypeItemName  
        //  item.Name : IsEnabled | item.Type : System.Boolean | propertyType : BackupItemTypeIsEnabled  
   // ==========================================================================


