//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:v2.0.50727
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

/*
This code was automatically generated at 02/26/2012 02:54:05 by 
        Jedzia's ViewModel generator.
Changes to this file may be lost if regeneration occurs.
http://xxx.com
*/
// Config = Debug DefaultNamespace = Jedzia.BackBock.ViewModel

using System.Collections.Generic;
using Jedzia.BackBock.SharedTypes;
using Jedzia.BackBock.Model.Data;
using Jedzia.BackBock.ViewModel.MainWindow;


namespace Jedzia.BackBock.ViewModel.Data
{

    /// <summary>
    /// The summary of BackupDataViewModel. BaseType: 
    /// </summary>
    public partial class BackupDataViewModel : ViewModelBase
    {
        internal BackupData backupdata;

        public BackupDataViewModel(BackupData backupData)
        {
            this.backupdata = backupData;
        }

        // BackupItem. HasFacets: False AttrQName: 
        //                   propertyType: System.Collections.ObjectModel.ObservableCollection<BackupItemType>, IsChoiceRoot: False, BaseType: 
        //                   ListType: None, HasCommonBaseType: False, xxxx: 
        /// <summary>
        /// The summary. 
        /// </summary>
        private System.Collections.ObjectModel.ObservableCollection<BackupItemViewModel> backupitem;

        public System.Collections.ObjectModel.ObservableCollection<BackupItemViewModel> BackupItems
        {
            get
            {
                if (this.backupitem == null)
                {
                    this.backupitem = new System.Collections.ObjectModel.ObservableCollection<BackupItemViewModel>();
                    foreach (var item in this.backupdata.BackupItem)
                    {
                        var colItem = new BackupItemViewModel(item);
                        colItem.PropertyChanged += OnDataPropertyChanged;
                        this.backupitem.Add(colItem);
                    }
                    this.backupitem.CollectionChanged += OnBackupItemCollectionChanged;
                }
                return this.backupitem;
            }
        }

        protected virtual void OnBackupItemCollectionChanged(object sender, System.Collections.Specialized.NotifyCollectionChangedEventArgs e)
        {
            BackupItemCollectionChanged(sender, e);
        }

        partial void BackupItemCollectionChanged(object sender, System.Collections.Specialized.NotifyCollectionChangedEventArgs e);

        // DatasetName. HasFacets: False AttrQName: 
        //                   propertyType: System.String, IsChoiceRoot: False, BaseType: 
        //                   ListType: None, HasCommonBaseType: False, xxxx: 
        /// <summary>
        /// Gets or sets the DatasetName. HasFacets: False AttrQName: 
        /// </summary> // Attribute
        /// <value>The DatasetName.</value>
        public System.String DatasetName
        {
            get
            {
                return this.backupdata.DatasetName;
            }

            set
            {
                if (this.backupdata.DatasetName == value)
                {
                    return;
                }
                this.backupdata.DatasetName = value;
                RaisePropertyChanged("DatasetName");
            }
        }

        protected virtual void OnDataPropertyChanged(object sender, System.ComponentModel.PropertyChangedEventArgs e)
        {
            DataPropertyChanged(sender, e);
        }

        partial void DataPropertyChanged(object sender, System.ComponentModel.PropertyChangedEventArgs e);

        public BackupDataViewModel Clone()
        {
            return (BackupDataViewModel)this.MemberwiseClone();
        }
    } 
}
