//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:v2.0.50727
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

/*
This code was automatically generated at 02/26/2012 02:54:05 by 
        Jedzia's ViewModel generator.
Changes to this file may be lost if regeneration occurs.
http://xxx.com
*/
// Config = Debug DefaultNamespace = Jedzia.BackBock.ViewModel

using System.Collections.Generic;
using Jedzia.BackBock.SharedTypes;
using Jedzia.BackBock.Model.Data;
using Jedzia.BackBock.ViewModel.MainWindow;


namespace Jedzia.BackBock.ViewModel.Data
{

    /// <summary>
    /// The summary of TaskViewModel. BaseType: 
    /// </summary>
    public partial class TaskViewModel : ViewModelBase
    {
        internal TaskType task;

        public TaskViewModel(TaskType task)
        {
            this.task = task;
        }

        // TypeName. HasFacets: False AttrQName: 
        //                   propertyType: System.String, IsChoiceRoot: False, BaseType: 
        //                   ListType: None, HasCommonBaseType: False, xxxx: 
        /// <summary>
        /// Gets or sets the TypeName. HasFacets: False AttrQName: 
        /// </summary> // Attribute
        /// <value>The TypeName.</value>
        public System.String TypeName
        {
            get
            {
                return this.task.TypeName;
            }

            set
            {
                if (this.task.TypeName == value)
                {
                    return;
                }
                this.task.TypeName = value;
                RaisePropertyChanged("TypeName");
            }
        }

        protected virtual void OnDataPropertyChanged(object sender, System.ComponentModel.PropertyChangedEventArgs e)
        {
            DataPropertyChanged(sender, e);
        }

        partial void DataPropertyChanged(object sender, System.ComponentModel.PropertyChangedEventArgs e);

        public TaskViewModel Clone()
        {
            return (TaskViewModel)this.MemberwiseClone();
        }
    } 
}
