//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:v2.0.50727
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

/*
This code was automatically generated at 02/26/2012 07:08:41 by 
        Jedzia's ViewModel generator.
Changes to this file may be lost if regeneration occurs.
http://xxx.com
*/
// Config = Debug DefaultNamespace = Jedzia.BackBock.ViewModel

using System.Collections.Generic;
using Jedzia.BackBock.SharedTypes;
using Jedzia.BackBock.Model.Data;
using Jedzia.BackBock.ViewModel.MainWindow;


namespace Jedzia.BackBock.ViewModel.Data
{

    /// <summary>
    /// The summary of PathViewModel. BaseType: 
    /// </summary>
    public partial class PathViewModel : ViewModelBase
    {
        internal PathDataType data;

        /// <summary>
        /// Initializes a new instance of the <see cref="PathViewModel"/> class.
        /// </summary>
        /// <param name="path">The path.</param>
        public PathViewModel(PathDataType path)
        {
            this.data = path;
        }

        // Exclusion. HasFacets: False AttrQName: 
        //                   propertyType: System.Collections.ObjectModel.ObservableCollection<Wildcard>, IsChoiceRoot: False, BaseType: 
        //                   ListType: None, HasCommonBaseType: False, xxxx: 
        /// <summary>
        /// The summary. 
        /// </summary>
        private System.Collections.ObjectModel.ObservableCollection<ExclusionViewModel> exclusion;

        /// <summary>
        /// Gets the exclusions.
        /// </summary>
        public System.Collections.ObjectModel.ObservableCollection<ExclusionViewModel> Exclusions
        {
            get
            {
                if (this.exclusion == null)
                {
                    this.exclusion = new System.Collections.ObjectModel.ObservableCollection<ExclusionViewModel>();
                    foreach (var item in this.data.Exclusion)
                    {
                        var colItem = new ExclusionViewModel(item);
                        colItem.PropertyChanged += OnDataPropertyChanged;
                        this.exclusion.Add(colItem);
                    }
                    this.exclusion.CollectionChanged += OnExclusionCollectionChanged;
                }
                return this.exclusion;
            }
        }

        /// <summary>
        /// Called when [exclusion collection changed].
        /// </summary>
        /// <param name="sender">The sender.</param>
        /// <param name="e">The <see cref="System.Collections.Specialized.NotifyCollectionChangedEventArgs"/> instance containing the event data.</param>
        protected virtual void OnExclusionCollectionChanged(object sender, System.Collections.Specialized.NotifyCollectionChangedEventArgs e)
        {
            ExclusionCollectionChanged(sender, e);
        }

        /// <summary>
        /// Exclusions the collection changed.
        /// </summary>
        /// <param name="sender">The sender.</param>
        /// <param name="e">The <see cref="System.Collections.Specialized.NotifyCollectionChangedEventArgs"/> instance containing the event data.</param>
        partial void ExclusionCollectionChanged(object sender, System.Collections.Specialized.NotifyCollectionChangedEventArgs e);

        // Inclusion. HasFacets: False AttrQName: 
        //                   propertyType: System.Collections.ObjectModel.ObservableCollection<Wildcard>, IsChoiceRoot: False, BaseType: 
        //                   ListType: None, HasCommonBaseType: False, xxxx: 
        /// <summary>
        /// The summary. 
        /// </summary>
        private System.Collections.ObjectModel.ObservableCollection<InclusionViewModel> inclusion;

        /// <summary>
        /// Gets the inclusions.
        /// </summary>
        public System.Collections.ObjectModel.ObservableCollection<InclusionViewModel> Inclusions
        {
            get
            {
                if (this.inclusion == null)
                {
                    this.inclusion = new System.Collections.ObjectModel.ObservableCollection<InclusionViewModel>();
                    foreach (var item in this.data.Inclusion)
                    {
                        var colItem = new InclusionViewModel(item);
                        colItem.PropertyChanged += OnDataPropertyChanged;
                        this.inclusion.Add(colItem);
                    }
                    this.inclusion.CollectionChanged += OnInclusionCollectionChanged;
                }
                return this.inclusion;
            }
        }

        /// <summary>
        /// Called when [inclusion collection changed].
        /// </summary>
        /// <param name="sender">The sender.</param>
        /// <param name="e">The <see cref="System.Collections.Specialized.NotifyCollectionChangedEventArgs"/> instance containing the event data.</param>
        protected virtual void OnInclusionCollectionChanged(object sender, System.Collections.Specialized.NotifyCollectionChangedEventArgs e)
        {
            InclusionCollectionChanged(sender, e);
        }

        /// <summary>
        /// Inclusions the collection changed.
        /// </summary>
        /// <param name="sender">The sender.</param>
        /// <param name="e">The <see cref="System.Collections.Specialized.NotifyCollectionChangedEventArgs"/> instance containing the event data.</param>
        partial void InclusionCollectionChanged(object sender, System.Collections.Specialized.NotifyCollectionChangedEventArgs e);

        // Path. HasFacets: False AttrQName: 
        //                   propertyType: System.String, IsChoiceRoot: False, BaseType: 
        //                   ListType: None, HasCommonBaseType: False, xxxx: 
        /// <summary>
        /// Gets or sets the Path. HasFacets: False AttrQName:
        /// </summary>
        /// <value>
        /// The Path.
        /// </value>
        /// // Attribute
        public System.String Path
        {
            get
            {
                return this.data.Path;
            }

            set
            {
                if (this.data.Path == value)
                {
                    return;
                }
                this.data.Path = value;
                RaisePropertyChanged("Path");
            }
        }

        // UserData. HasFacets: False AttrQName: 
        //                   propertyType: System.String, IsChoiceRoot: False, BaseType: 
        //                   ListType: None, HasCommonBaseType: False, xxxx: 
        /// <summary>
        /// Gets or sets the UserData. HasFacets: False AttrQName:
        /// </summary>
        /// <value>
        /// The UserData.
        /// </value>
        /// // Attribute
        public System.String UserData
        {
            get
            {
                return this.data.UserData;
            }

            set
            {
                if (this.data.UserData == value)
                {
                    return;
                }
                this.data.UserData = value;
                RaisePropertyChanged("UserData");
            }
        }

        /// <summary>
        /// Called when [data property changed].
        /// </summary>
        /// <param name="sender">The sender.</param>
        /// <param name="e">The <see cref="System.ComponentModel.PropertyChangedEventArgs"/> instance containing the event data.</param>
        protected virtual void OnDataPropertyChanged(object sender, System.ComponentModel.PropertyChangedEventArgs e)
        {
            DataPropertyChanged(sender, e);
        }

        /// <summary>
        /// Datas the property changed.
        /// </summary>
        /// <param name="sender">The sender.</param>
        /// <param name="e">The <see cref="System.ComponentModel.PropertyChangedEventArgs"/> instance containing the event data.</param>
        partial void DataPropertyChanged(object sender, System.ComponentModel.PropertyChangedEventArgs e);

        /// <summary>
        /// Clones this instance.
        /// </summary>
        /// <returns></returns>
        public PathViewModel Clone()
        {
            return (PathViewModel)this.MemberwiseClone();
        }
    } 
}
