//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:v2.0.50727
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

/*
This code was automatically generated at 02/19/2012 01:24:50 by 
        Jedzia's ViewModel generator.
Changes to this file may be lost if regeneration occurs.
http://xxx.com
*/
// Config = Debug DefaultNamespace = Jedzia.BackBock.ViewModel

using System.Collections.Generic;
using Jedzia.BackBock.SharedTypes;
using Jedzia.BackBock.Model.Data;
using Jedzia.BackBock.ViewModel.MainWindow;


namespace Jedzia.BackBock.ViewModel.Data
{

    /// <summary>
    /// The summary of BackupItemViewModel. BaseType: 
    /// </summary>
    public partial class BackupItemViewModel : ViewModelBase
    {
        internal BackupItem backupitem;

        public BackupItemViewModel(BackupItem backupItem)
        {
            this.backupitem = backupItem;
        }

        // Name. HasFacets: False AttrQName: 
        //                   propertyType: System.String, IsChoiceRoot: False, BaseType: 
        //                   ListType: None, HasCommonBaseType: False, xxxx: 
        /// <summary>
        /// Gets or sets the Name. HasFacets: False AttrQName: 
        /// </summary> // Attribute
        /// <value>The Name.</value>
        public System.String Name
        {
            get
            {
                return this.backupitem.Name;
            }

            set
            {
                if (this.backupitem.Name == value)
                {
                    return;
                }
                this.backupitem.Name = value;
                RaisePropertyChanged("Name");
            }
        }

        // IsEnabled. HasFacets: False AttrQName: 
        //                   propertyType: System.Boolean, IsChoiceRoot: False, BaseType: 
        //                   ListType: None, HasCommonBaseType: False, xxxx: 
        /// <summary>
        /// Gets or sets the IsEnabled. HasFacets: False AttrQName: 
        /// </summary> // Attribute
        /// <value>The IsEnabled.</value>
        public System.Boolean IsEnabled
        {
            get
            {
                return this.backupitem.IsEnabled;
            }

            set
            {
                if (this.backupitem.IsEnabled == value)
                {
                    return;
                }
                this.backupitem.IsEnabled = value;
                RaisePropertyChanged("IsEnabled");
            }
        }

        // Test. HasFacets: False AttrQName: 
        //                   propertyType: System.String, IsChoiceRoot: False, BaseType: 
        //                   ListType: None, HasCommonBaseType: False, xxxx: 
        /// <summary>
        /// Gets or sets the Test. HasFacets: False AttrQName: 
        /// </summary> // Attribute
        /// <value>The Test.</value>
        public System.String Test
        {
            get
            {
                return this.backupitem.Test;
            }

            set
            {
                if (this.backupitem.Test == value)
                {
                    return;
                }
                this.backupitem.Test = value;
                RaisePropertyChanged("Test");
            }
        }

        // IsInterface. HasFacets: False AttrQName: 
        //                   propertyType: System.Boolean, IsChoiceRoot: False, BaseType: 
        //                   ListType: None, HasCommonBaseType: False, xxxx: 
        /// <summary>
        /// Gets or sets the IsInterface. HasFacets: False AttrQName: 
        /// </summary> // Attribute
        /// <value>The IsInterface.</value>
        public System.Boolean IsInterface
        {
            get
            {
                return this.backupitem.IsInterface;
            }

            set
            {
                if (this.backupitem.IsInterface == value)
                {
                    return;
                }
                this.backupitem.IsInterface = value;
                RaisePropertyChanged("IsInterface");
            }
        }

        protected virtual void OnDataPropertyChanged(object sender, System.ComponentModel.PropertyChangedEventArgs e)
        {
            DataPropertyChanged(sender, e);
        }

        partial void DataPropertyChanged(object sender, System.ComponentModel.PropertyChangedEventArgs e);

        public BackupItemViewModel Clone()
        {
            return (BackupItemViewModel)this.MemberwiseClone();
        }
    } 
}
