
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:v2.0.50727
//     ViewModelGenerator:v1.0
//
//     Changes to this and other generated files may cause incorrect behavior 
//     and will be lost if the code is regenerated.
// </auto-generated>
//
// Important: 
// This code generator needs a registry key set to run. Make sure
// HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\VisualStudio\9.0\TextTemplating\IncludeFolders\.tt\IncludeJedziaT4Tools
// points to the location of the T4 Directory, e.g. "D:\JedziaT4Tools\T4" (without the quotes). 
// Then create a system environment variable with the name "JEDZIAT4TOOLS" and point it to the same
// location as the T4-Include registry key.
//------------------------------------------------------------------------------



   // ==========================================================================
   // vmodel.Name : ClassDataItem | vmodel.Type : ClassDataItem | 

        //  item.Name : ItemType | item.Type : System.String | propertyType : ClassDataItemItemType  
        //  item.Name : Name | item.Type : System.String | propertyType : ClassDataItemName  
        //  item.Name : Color | item.Type : System.String | propertyType : ClassDataItemColor  
        //  item.Name : Scope | item.Type : System.String | propertyType : ClassDataItemScope  
        //  item.Name : AccessSpecifier | item.Type : System.String | propertyType : ClassDataItemAccessSpecifier  
        //  item.Name : Static | item.Type : System.Boolean | propertyType : ClassDataItemStatic  
        //  item.Name : Signature | item.Type : System.String | propertyType : ClassDataItemSignature  
        //  item.Name : Parameternames | item.Type : System.String | propertyType : ClassDataItemParameternames  
        //  item.Name : ReturnType | item.Type : System.String | propertyType : ClassDataItemReturnType  
        //  item.Name : IsConstructor | item.Type : System.Boolean | propertyType : ClassDataItemIsConstructor  
        //  item.Name : DisplayData | item.Type : System.String | propertyType : ClassDataItemDisplayData  
   // ==========================================================================


   // ==========================================================================
   // vmodel.Name : ClassDataItemList | vmodel.Type : ClassDataItemList | 

        //  item.Name : ClassDataItem | item.Type : ClassDataItem | propertyType : ClassDataItemListClassDataItem  
        //  item.Name : Type | item.Type : System.String | propertyType : ClassDataItemListType  
        //  item.Name : Name | item.Type : System.String | propertyType : ClassDataItemListName  
        //  item.Name : Color | item.Type : System.String | propertyType : ClassDataItemListColor  
   // ==========================================================================


