//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:v2.0.50727
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

/*
This code was automatically generated at 02/19/2012 01:11:17 by 
        Jedzia's ViewModel generator.
Changes to this file may be lost if regeneration occurs.
http://xxx.com
*/
// Config = Debug DefaultNamespace = Jedzia.BackBock.ViewModel

using System.Collections.Generic;
using Jedzia.BackBock.Model.Data;


namespace Jedzia.BackBock.ViewModel.Data
{

    /// <summary>
    /// The summary of ClassDataItemListViewModel. BaseType: 
    /// </summary>
    public partial class ClassDataItemListViewModel : ViewModelBase
    {
        internal ClassDataItemList classdataitemlist;

        public ClassDataItemListViewModel(ClassDataItemList classDataItemList)
        {
            this.classdataitemlist = classDataItemList;
        }

        // ClassDataItem. HasFacets: False AttrQName: 
        //                   propertyType: System.Collections.ObjectModel.ObservableCollection<ClassDataItem>, IsChoiceRoot: False, BaseType: 
        //                   ListType: ObservableCollection, HasCommonBaseType: False, xxxx: 
        /// <summary>
        /// The summary. 
        /// </summary>
        private System.Collections.ObjectModel.ObservableCollection<ClassDataItemViewModel> classdataitem;

        public System.Collections.ObjectModel.ObservableCollection<ClassDataItemViewModel> ClassDataItems
        {
            get
            {
                if (this.classdataitem == null)
                {
                    this.classdataitem = new System.Collections.ObjectModel.ObservableCollection<ClassDataItemViewModel>();
                    foreach (var item in this.classdataitemlist.ClassDataItem)
                    {
                        var colItem = new ClassDataItemViewModel(item);
                        colItem.PropertyChanged += OnDataPropertyChanged;
                        this.classdataitem.Add(colItem);
                    }
                }
                return this.classdataitem;
            }
        }

        // Type. HasFacets: False AttrQName: 
        //                   propertyType: System.String, IsChoiceRoot: False, BaseType: 
        //                   ListType: None, HasCommonBaseType: False, xxxx: 
        /// <summary>
        /// Gets or sets the Type. HasFacets: False AttrQName: 
        /// </summary> // Attribute
        /// <value>The Type.</value>
        public System.String Type
        {
            get
            {
                return this.classdataitemlist.Type;
            }

            set
            {
                if (this.classdataitemlist.Type == value)
                {
                    return;
                }
                this.classdataitemlist.Type = value;
                RaisePropertyChanged("Type");
            }
        }

        // Name. HasFacets: False AttrQName: 
        //                   propertyType: System.String, IsChoiceRoot: False, BaseType: 
        //                   ListType: None, HasCommonBaseType: False, xxxx: 
        /// <summary>
        /// Gets or sets the Name. HasFacets: False AttrQName: 
        /// </summary> // Attribute
        /// <value>The Name.</value>
        public System.String Name
        {
            get
            {
                return this.classdataitemlist.Name;
            }

            set
            {
                if (this.classdataitemlist.Name == value)
                {
                    return;
                }
                this.classdataitemlist.Name = value;
                RaisePropertyChanged("Name");
            }
        }

        // Color. HasFacets: False AttrQName: 
        //                   propertyType: System.String, IsChoiceRoot: False, BaseType: 
        //                   ListType: None, HasCommonBaseType: False, xxxx: 
        /// <summary>
        /// Gets or sets the Color. HasFacets: False AttrQName: 
        /// </summary> // Attribute
        /// <value>The Color.</value>
        public System.String Color
        {
            get
            {
                return this.classdataitemlist.Color;
            }

            set
            {
                if (this.classdataitemlist.Color == value)
                {
                    return;
                }
                this.classdataitemlist.Color = value;
                RaisePropertyChanged("Color");
            }
        }

        protected virtual void OnDataPropertyChanged(object sender, System.ComponentModel.PropertyChangedEventArgs e)
        {
            DataPropertyChanged(sender, e);
        }

        partial void DataPropertyChanged(object sender, System.ComponentModel.PropertyChangedEventArgs e);

        public ClassDataItemListViewModel Clone()
        {
            return (ClassDataItemListViewModel)this.MemberwiseClone();
        }
    } 
}
